version: "3.9"

services:
  cricket-scoreboard:
    build: .
    ports:
      - "9090:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.score.rule=Host(`score.nirvanahome.dev`)"
      - "traefik.http.routers.score.entrypoints=websecure"
      - "traefik.http.services.score.loadbalancer.server.port=8000"
      - "traefik.http.routers.score.tls.certresolver=letsencrypt"
