services:
  scoreboard:
    build: .
    ports:
      - "9090:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.http.routers.scoreboard.rule=Host(`scoreboard.nirvanahome.dev`)
      - traefik.http.routers.scoreboard.entrypoints=websecure
      - traefik.http.services.scoreboard.loadbalancer.server.port=8000
      - traefik.http.routers.scoreboard.tls.certresolver=letsencrypt

